[project]
name = "echo-location"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi>=0.136.1",
    "load-dotenv>=0.1.0",
    "praw>=7.8.1",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.49",
    "types-requests>=2.33.0.20260408",
    "uvicorn>=0.46.0",
    "vadersentiment>=3.3.2",
]
